// Each marker–influence pair, with the public source that states it (SPEC.md section 18.4). Every quote
// was matched word for word against the page as downloaded on 7 October 2026 ("…" joins a list heading
// and its item). Left out because no allowed source states it for that marker: testosterone therapy and
// haematocrit or haemoglobin (only the red cell count page names it), free testosterone and the time of
// day, biotin and TSH, thyroid hormone medicine and TSH, iron supplements and ferritin, creatine and
// blood creatinine, statins and LDL by name.

import type { Influence, InfluenceSource } from './influences'

const ACCESSED = '2026-10-07'
const page = (title: string, url: string, quote: string): InfluenceSource => ({ title, url, quote, accessed: ACCESSED })

export const INFLUENCES: Influence[] = [
  { markers: ["testosterone"], influence: 'time-of-day', effect: 'vary', source: page("MedlinePlus: Testosterone Levels Test", 'https://medlineplus.gov/lab-tests/testosterone-levels-test/', "Your provider will take a blood sample in the morning, between 7 and 10. During these hours, your testosterone levels are typically the highest.") },
  { markers: ["haematocrit"], influence: 'dehydration', effect: 'raise', source: page("MedlinePlus: Hematocrit Test", 'https://medlineplus.gov/lab-tests/hematocrit-test/', "Dehydration, the most common cause of a high hematocrit") },
  { markers: ["haemoglobin"], influence: 'dehydration', effect: 'raise', source: page("Testing.com: Complete Blood Count (CBC)", 'https://www.testing.com/tests/complete-blood-count-cbc/', "Dehydration can raise your hematocrit and hemoglobin readings because there's less fluid in your blood.") },
  { markers: ["rbc"], influence: 'dehydration', effect: 'raise', source: page("MedlinePlus: Red Blood Cell (RBC) Count", 'https://medlineplus.gov/lab-tests/red-blood-cell-rbc-count/', "Conditions that may cause a high red blood cell count can include: … Dehydration") },
  { markers: ["haematocrit"], influence: 'smoking', effect: 'raise', source: page("Testing.com: Hematocrit", 'https://www.testing.com/tests/hematocrit/', "Smoking (reduces oxygen delivery, triggering more red blood cell production)") },
  { markers: ["haemoglobin"], influence: 'smoking', effect: 'raise', source: page("Testing.com: Hemoglobin", 'https://www.testing.com/tests/hemoglobin/', "causes can include issues that are not cancer, such as living at a high altitude, smoking, sleep apnea, inherited hemoglobin conditions, and dehydration") },
  { markers: ["rbc"], influence: 'smoking', effect: 'raise', source: page("Testing.com: Red Blood Cell Count (RBC)", 'https://www.testing.com/tests/red-blood-cell-count-rbc/', "A high RBC count may be due to: … Smoking") },
  { markers: ["haematocrit"], influence: 'altitude', effect: 'raise', source: page("MedlinePlus: Hematocrit Test", 'https://medlineplus.gov/lab-tests/hematocrit-test/', "Living at high altitudes with less oxygen in the air may cause a high hematocrit.") },
  { markers: ["haemoglobin"], influence: 'altitude', effect: 'raise', source: page("MedlinePlus: Hemoglobin Test", 'https://medlineplus.gov/lab-tests/hemoglobin-test/', "Living at a higher altitude can also cause a high hemoglobin level.") },
  { markers: ["haematocrit"], influence: 'pregnancy', effect: 'lower', source: page("MedlinePlus: Hematocrit Test", 'https://medlineplus.gov/lab-tests/hematocrit-test/', "Pregnancy can cause a low hematocrit.") },
  { markers: ["rbc"], influence: 'testosterone', effect: 'raise', source: page("Testing.com: Red Blood Cell Count (RBC)", 'https://www.testing.com/tests/red-blood-cell-count-rbc/', "A high RBC count may be due to: … Certain drugs (Anabolic steroids, Erythropoietin, Gentamicin, Testosterone, Methyldopa)") },
  { markers: ["glucose"], influence: 'eating', effect: 'raise', source: page("Testing.com: Comprehensive Metabolic Panel (CMP)", 'https://www.testing.com/tests/comprehensive-metabolic-panel-cmp/', "Fasting matters most for the glucose reading. Eating beforehand can push blood sugar higher and make that result harder to read.") },
  { markers: ["glucose"], influence: 'corticosteroid', effect: 'raise', source: page("MedlinePlus: Blood Glucose Test", 'https://medlineplus.gov/lab-tests/blood-glucose-test/', "Examples of medicines that may cause high blood glucose in some people include certain types of: … Steroids") },
  { markers: ["glucose"], influence: 'statin', effect: 'raise', source: page("MedlinePlus: Blood Glucose Test", 'https://medlineplus.gov/lab-tests/blood-glucose-test/', "Examples of medicines that may cause high blood glucose in some people include certain types of: … Statins") },
  { markers: ["triglycerides"], influence: 'eating', effect: 'raise', source: page("Testing.com: Triglycerides", 'https://www.testing.com/tests/triglycerides/', "Recent food, especially carbohydrates, sugar, and fat, temporarily raises triglyceride levels and can produce a falsely high result.") },
  { markers: ["triglycerides"], influence: 'alcohol', effect: 'raise', source: page("Testing.com: Triglycerides", 'https://www.testing.com/tests/triglycerides/', "Alcohol converts to triglycerides in the liver and can push levels high even after an overnight fast.") },
  { markers: ["triglycerides"], influence: 'corticosteroid', effect: 'raise', source: page("Testing.com: Triglycerides", 'https://www.testing.com/tests/triglycerides/', "Beta-blockers, corticosteroids, and thiazide diuretics can raise triglyceride levels") },
  { markers: ["alt"], influence: 'hard-exercise', effect: 'raise', source: page("Testing.com: Alanine Aminotransferase (ALT)", 'https://www.testing.com/tests/alanine-aminotransferase-alt/', "Intense or extreme exercise can cause a temporary increase in ALT levels.") },
  { markers: ["ast"], influence: 'hard-exercise', effect: 'raise', source: page("Testing.com: Aspartate Aminotransferase (AST)", 'https://www.testing.com/tests/aspartate-aminotransferase-ast/', "Intense exercise, a heart attack, muscle injury, and certain medications can all raise AST without any liver disease.") },
  { markers: ["alt", "ast"], influence: 'alcohol', effect: 'raise', source: page("Testing.com: Liver Panel", 'https://www.testing.com/tests/liver-panel/', "Heavy alcohol use and intense exercise in the day or two before the draw can raise AST and ALT temporarily.") },
  { markers: ["alt", "ast"], influence: 'statin', effect: 'raise', source: page("Testing.com: Comprehensive Metabolic Panel (CMP)", 'https://www.testing.com/tests/comprehensive-metabolic-panel-cmp/', "Statins can raise liver enzymes (ALT, AST).") },
  { markers: ["free-t4"], influence: 'biotin', effect: 'affect', source: page("Testing.com: Free T4 Test", 'https://www.testing.com/tests/free-t4-test/', "High-dose biotin (vitamin B7) supplements can cause a falsely high result on some immunoassay platforms.") },
  { markers: ["free-t4"], influence: 'thyroid-hormone', effect: 'raise', source: page("Testing.com: Free T4 Test", 'https://www.testing.com/tests/free-t4-test/', "levothyroxine can cause a temporary rise in free T4 for a few hours afterward") },
  { markers: ["tsh"], influence: 'time-of-day', effect: 'vary', source: page("Testing.com: Thyroid-Stimulating Hormone (TSH)", 'https://www.testing.com/tests/thyroid-stimulating-hormone-tsh/', "TSH follows a daily rhythm, peaking in the early morning and dropping in the afternoon, though the variation is usually small.") },
  { markers: ["ferritin"], influence: 'illness', effect: 'raise', source: page("MedlinePlus: Ferritin Blood Test", 'https://medlineplus.gov/lab-tests/ferritin-blood-test/', "Other conditions that may cause increased ferritin levels include: … Inflammation (like from infection or surgery)") },
  { markers: ["vitamin-d"], influence: 'vitamin-d', effect: 'raise', source: page("MedlinePlus: Vitamin D Test", 'https://medlineplus.gov/lab-tests/vitamin-d-test/', "If your total vitamin D levels are high or toxic, it usually means you're getting too much from supplements.") },
  { markers: ["crp"], influence: 'illness', effect: 'raise', source: page("MedlinePlus: C-Reactive Protein (CRP) Test", 'https://medlineplus.gov/lab-tests/c-reactive-protein-crp-test/', "High CRP levels may mean you have an acute or chronic health condition, such as: … Infections from bacteria or viruses.") },
  { markers: ["crp"], influence: 'hard-exercise', effect: 'raise', source: page("Testing.com: C-Reactive Protein (CRP)", 'https://www.testing.com/tests/c-reactive-protein-crp/', "Such activities can cause a sudden jump in the CRP level.") },
  { markers: ["wbc"], influence: 'illness', effect: 'raise', source: page("MedlinePlus: White Blood Count (WBC)", 'https://medlineplus.gov/lab-tests/white-blood-count-wbc/', "Conditions that may cause a high white blood count, also called leukocytosis, include: … An infection") },
  { markers: ["wbc"], influence: 'smoking', effect: 'raise', source: page("MedlinePlus: White Blood Count (WBC)", 'https://medlineplus.gov/lab-tests/white-blood-count-wbc/', "Smoking, stress, a reaction to a medicine, or pregnancy may also cause your body to make more white blood cells") },
  { markers: ["wbc"], influence: 'corticosteroid', effect: 'raise', source: page("MedlinePlus: Blood Differential", 'https://medlineplus.gov/lab-tests/blood-differential/', "Conditions that may cause a high white blood cell count, also called leukocytosis, can include: … Certain steroids") },
  { markers: ["creatinine"], influence: 'dehydration', effect: 'raise', source: page("MedlinePlus: Creatinine Test", 'https://medlineplus.gov/lab-tests/creatinine-test/', "They may be caused by dehydration, muscle disorders and injuries, muscular dystrophy, intense exercise, or a diet high in meat.") },
  { markers: ["creatinine"], influence: 'hard-exercise', effect: 'raise', source: page("MedlinePlus: Creatinine Test", 'https://medlineplus.gov/lab-tests/creatinine-test/', "They may be caused by dehydration, muscle disorders and injuries, muscular dystrophy, intense exercise, or a diet high in meat.") },
  { markers: ["urea", "bun"], influence: 'dehydration', effect: 'raise', source: page("MedlinePlus: BUN (Blood Urea Nitrogen)", 'https://medlineplus.gov/lab-tests/bun-blood-urea-nitrogen/', "A few other reasons your BUN level might be higher than normal include: … Dehydration (too little fluid in your body)") },
  { markers: ["cholesterol-total"], influence: 'statin', effect: 'lower', source: page("NHS: Statins", 'https://www.nhs.uk/medicines/statins/', "Statins are medicines used to lower cholesterol.") },
  { markers: ["hdl"], influence: 'smoking', effect: 'lower', source: page("MedlinePlus: Cholesterol Levels", 'https://medlineplus.gov/lab-tests/cholesterol-levels/', "Smoking lowers your HDL (good) cholesterol, especially in women.") },
  { markers: ["ldl"], influence: 'smoking', effect: 'raise', source: page("MedlinePlus: Cholesterol Levels", 'https://medlineplus.gov/lab-tests/cholesterol-levels/', "Smoking also raises your LDL (bad) cholesterol.") },
  { markers: ["cortisol"], influence: 'time-of-day', effect: 'vary', source: page("MedlinePlus: Cortisol Test", 'https://medlineplus.gov/lab-tests/cortisol-test/', "once in the morning when cortisol levels are normally at their highest, and again around 4 p.m., when levels are normally much lower.") },
  { markers: ["cortisol"], influence: 'hard-exercise', effect: 'raise', source: page("MedlinePlus: Cortisol Test", 'https://medlineplus.gov/lab-tests/cortisol-test/', "Stress and exercise can raise your cortisol levels") },
  { markers: ["psa"], influence: 'hard-exercise', effect: 'raise', source: page("NHS: PSA test", 'https://www.nhs.uk/tests-and-treatments/psa-test/', "These can increase your PSA levels which could make the test less accurate.") },
]
